Dev/deploy from catalog
SkylineCommunications/Skyline.DataMiner.CICD.Tools.DataMinerDeploy pull request #1
Opened 2023-12-13 14:28 UTC by janstaelensskyline

2023-12-14 10:39 UTC, MichielOda requested changes

2023-12-14 10:39 UTC, MichielOda commented on CICD.Tools.DataMinerDeploy.LibTests/CICD.Tools.DataMinerDeploy.LibTests.csproj
> +  </ItemGroup>
```suggestion
  <ItemGroup>
    <PackageReference Include="Extensions.Logging.Mock" Version="1.2.1" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
  </ItemGroup>
```

2023-12-14 10:39 UTC, MichielOda commented on CICD.Tools.DataminerDeploy/Program.cs
> +			var FromArtifact = new Command("FromArtifact", "Deploys a specific package from a local .dmapp to a DataMiner agent.")
Please use camelCase for variables. I would suggest to change the command to 'from-artifact'.

2023-12-14 10:39 UTC, MichielOda commented on CICD.Tools.DataminerDeploy/Program.cs
> +			if (string.IsNullOrWhiteSpace(dmCatalogToken))
```suggestion
			if (String.IsNullOrWhiteSpace(dmCatalogToken))
```

2023-12-14 10:39 UTC, MichielOda commented on CICD.Tools.DataminerDeploy/Program.cs
> +				deployTimeout = int.MaxValue; // MaxValue
```suggestion
				deployTimeout = Int32.MaxValue; // MaxValue
```

2023-12-14 10:39 UTC, MichielOda commented on CICD.Tools.DataminerDeploy/Program.cs
> +			var FromCatalog = new Command("FromCatalog", "Deploys a specific package from the cloud to a cloud-connected DataMiner agent. Currently only supports private artifacts uploaded using a key from th
Please use camelCase for variables. I would also suggest to change the sub command to 'from-catalog'.

2023-12-14 10:39 UTC, MichielOda commented on CICD.Tools.DataminerDeploy/LICENSE.txt
Update to new license with the metrics clause

2023-12-14 10:39 UTC, MichielOda commented on CICD.Tools.DataminerDeploy/CICD.Tools.DataminerDeploy.csproj
> +		<PackageTags>Skyline;DataMiner</PackageTags>
```suggestion
		<Nullable>disable</Nullable>
		<AssemblyName>Skyline.DataMiner.CICD.Tools.DataMinerDeploy</AssemblyName>
		<RootNamespace>Skyline.DataMiner.CICD.Tools.DataMinerDeploy</RootNamespace>
		<PackageTags>Skyline;DataMiner;CICD</PackageTags>
```

2023-12-14 10:39 UTC, MichielOda commented on CICD.Tools.DataminerDeploy/CICD.Tools.DataminerDeploy.csproj
> +	</ItemGroup>
```suggestion
	<ItemGroup>
		<PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
		<PackageReference Include="Skyline.DataMiner.CICD.FileSystem" Version="1.0.1" />
		<PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
	</ItemGroup>
```

2023-12-14 10:39 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/CICD.Tools.DataminerDeploy.Lib.csproj
> +		<PackageTags>Skyline;DataMiner</PackageTags>
```suggestion
		<Nullable>disable</Nullable>
		<AssemblyName>Skyline.DataMiner.CICD.Tools.DataMinerDeploy.Lib</AssemblyName>
		<RootNamespace>Skyline.DataMiner.CICD.Tools.DataMinerDeploy.Lib</RootNamespace>
		<PackageTags>Skyline;DataMiner;CICD</PackageTags>
```

2023-12-14 10:39 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/CICD.Tools.DataminerDeploy.Lib.csproj
> +	  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.24" />
Package is deprecated. Apparently we need to use Azure.Core instead.

2023-12-14 10:39 UTC, MichielOda commented on CICD.Tools.DataMinerDeploy.LibTests/DeploymentFactoryTests.cs
Unit tests fail for me with this error: Requested registry access is not allowed.

2023-12-14 10:39 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/CatalogService/CatalogServiceFactory.cs
> +			httpClient.BaseAddress = new Uri($"{apiBaseUrl}");
```suggestion
			httpClient.BaseAddress = new Uri(apiBaseUrl);
```

2023-12-14 10:39 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/CatalogService/CatalogServiceFactory.cs
> +			var environment = Environment.GetEnvironmentVariable("Skyline-deploy-action-namespace");
Generally environment variables are upper case: [wikipedia](https://en.wikipedia.org/wiki/Environment_variable#:~:text=It%20is%20conventional,2%2C%20and%20Windows.)

2023-12-14 10:39 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/CatalogService/HttpCatalogService.cs
> +				res = await _deployArtifactApi.DeployArtifactWithApiKeyFunctionWithHttpMessagesAsync(new DeployArtifactAsSystemForm(artifactIdentifier), key);
Async method has an option to pass the cancellation token

2023-12-14 10:39 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/CatalogService/HttpCatalogService.cs
> +				throw new InvalidOperationException("Received an invalid deployment ID");
Style code: blank line after bracket (other locations as well)

2023-12-14 10:39 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/CatalogService/HttpCatalogService.cs
> +			var responseContent = string.Empty;
```suggestion
			var responseContent = String.Empty;
```

2023-12-14 10:39 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/DataMinerArtifacts/CatalogArtifact.cs
Same feedback for env variables as before. In addition, maybe make it a const somewhere so that if it needs to be changed, you don't need to update each location separately.

2023-12-14 10:39 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/DataMinerArtifacts/CatalogArtifact.cs
> +						string keyFromWinEncryptedKeys = new System.Net.NetworkCredential(string.Empty, encryptedKey).Password;
```suggestion
						string keyFromWinEncryptedKeys = new System.Net.NetworkCredential(String.Empty, encryptedKey).Password;
```

2023-12-14 10:39 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/DataMinerArtifacts/CatalogArtifact.cs
> +							keyFromEnv = keyFromWinEncryptedKeys;
Missing return? As you got the key so no need to execute the other part below.

2023-12-14 10:39 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/DataMinerArtifacts/IArtifact.cs
> +using System.Threading.Tasks;
usings inside namespace

2023-12-14 10:39 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/DeploymentFactory.cs
> +﻿using Microsoft.Extensions.Logging;
using inside namespace

2023-12-14 10:39 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/Models/DeployedPackage.cs
> +		public string Status { get; set; }
```suggestion
		public string Status { get; }
```

2023-12-14 12:18 UTC, janstaelensskyline commented on CICD.Tools.DataminerDeploy/Program.cs
> +			var FromArtifact = new Command("FromArtifact", "Deploys a specific package from a local .dmapp to a DataMiner agent.")
camelcase OK, I would like to avoid special characters for the commandline though. This to avoid wierd behavior on groovy, linux, windows, concourse, github, azure, ... wherever they execute from. The less special tokens, the more robust.

2023-12-14 12:19 UTC, janstaelensskyline commented on CICD.Tools.DataminerDeploy/Program.cs
> +			var FromCatalog = new Command("FromCatalog", "Deploys a specific package from the cloud to a cloud-connected DataMiner agent. Currently only supports private artifacts uploaded using a key from th
camelcase OK, I would like to avoid special characters for the commandline though. This to avoid wierd behavior on groovy, linux, windows, concourse, github, azure, ... wherever they execute from. The less special tokens, the more robust.

2023-12-14 12:21 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/DataMinerArtifacts/CatalogArtifact.cs
> +							keyFromEnv = keyFromWinEncryptedKeys;
Not a missing return. It should prioritize the key from dmcatalogtoken if it exists. so overwrites it. I also want to debug log if that override happens so the user is aware. I've added a comment to make that more clear

2023-12-14 12:22 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/DataMinerArtifacts/IArtifact.cs
> +using System.Threading.Tasks;
Done, do you happen to know if there's a way to change the default behavior of VS to put them under the namespace iso above it?

2023-12-14 12:22 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/DeploymentFactory.cs
> +﻿using Microsoft.Extensions.Logging;
done

2023-12-14 13:09 UTC, MichielOda commented on CICD.Tools.DataminerDeploy/Program.cs
> +			var FromArtifact = new Command("FromArtifact", "Deploys a specific package from a local .dmapp to a DataMiner agent.")
![image](https://github.com/SkylineCommunications/Skyline.DataMiner.CICD.Tools.DataMinerDeploy/assets/97458010/d1b57895-ffe0-406f-b69d-eafc7f587d97)
The main command already has dashes as well. Even dotnet commands contain dashes. 
![image](https://github.com/SkylineCommunications/Skyline.DataMiner.CICD.Tools.DataMinerDeploy/assets/97458010/e63b61bd-d5a1-4605-9dab-79e5d633989d)

2023-12-14 13:19 UTC, janstaelensskyline commented on CICD.Tools.DataMinerDeploy.LibTests/DeploymentFactoryTests.cs
You need to run your visual studio as administrator

2023-12-14 13:19 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/CatalogService/CatalogServiceFactory.cs
> +			var environment = Environment.GetEnvironmentVariable("Skyline-deploy-action-namespace");
done

2023-12-14 13:21 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/CatalogService/HttpCatalogService.cs
> +				res = await _deployArtifactApi.DeployArtifactWithApiKeyFunctionWithHttpMessagesAsync(new DeployArtifactAsSystemForm(artifactIdentifier), key);
OK

2023-12-14 13:22 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/CatalogService/HttpCatalogService.cs
> +				throw new InvalidOperationException("Received an invalid deployment ID");
OK

2023-12-14 13:27 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/CICD.Tools.DataminerDeploy.Lib.csproj
> +	  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.24" />
It doesn't recognize HttpOperationResponse  which is part of the generated code coming from swagger when we use Azure.Core. 

Would prefer to stick to the clientRunTime for the first release at least. That code is well-tested from usage in the GitHub deploy action.

https://stackoverflow.com/questions/77401708/how-to-migrate-from-microsoft-rest-clientruntime-to-azure-core

2023-12-14 13:30 UTC, janstaelensskyline commented on CICD.Tools.DataminerDeploy/Program.cs
> +			var FromArtifact = new Command("FromArtifact", "Deploys a specific package from a local .dmapp to a DataMiner agent.")
I still prefer to use PascalCase for the subcommand. It looks more natural to consider that the same like calling a Method. The main command dataminer-package-deploy is better differentiated from its subcommand then.

2023-12-15 12:46 UTC, janstaelensskyline commented on CICD.Tools.DataminerDeploy/Program.cs
> +			var FromArtifact = new Command("FromArtifact", "Deploys a specific package from a local .dmapp to a DataMiner agent.")
As discussed in person. Microsoft has official guidelines: https://learn.microsoft.com/en-us/dotnet/standard/commandline/syntax#design-guidance

as such we'll follow those standards and I've indeed adjusted the arguments to use Kebab-Case names.

2023-12-19 15:11 UTC, MichielOda requested changes

2023-12-19 15:11 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/DataMinerArtifacts/CatalogArtifact.cs
> +							keyFromEnv = keyFromWinEncryptedKeys;
I don't really understand why it should be able to be overridden? Currently the safer option (encrypted) is less preferred then the unencrypted one?

2023-12-19 15:11 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/DataMinerArtifacts/IArtifact.cs
> +using System.Threading.Tasks;
https://stackoverflow.com/a/66772071

2023-12-19 15:11 UTC, MichielOda commented on CICD.Tools.DataminerDeploy/Program.cs
> +	/// Deploys a package to DataMiner from the catalog or directly..
```suggestion
	/// Deploys a package to DataMiner from the catalog or directly.
```

2023-12-19 15:11 UTC, MichielOda commented on CICD.Tools.DataminerDeploy/Program.cs
> +			description: "The unique cloud artifact identifier as returned from performing a catalog-upload. e.g. dmscript/f764389f-5404-4c32-9ac9-b54366a3d5e0")
Is this a fictional guid or an actual artifact?

2023-12-19 15:11 UTC, MichielOda commented on CICD.Tools.DataminerDeploy/Program.cs
> +			var fromArtifact = new Command("from-artifact", "Deploys a specific package from a local .dmapp to a DataMiner agent.")
Maybe comment out the artifact parts as currently this will be blocked.

2023-12-19 15:11 UTC, MichielOda commented on CICD.Tools.DataminerDeploy/README.md
> +dataminer-package-deploy from-catalog --artifact-id "dmscript/f764389f-5404-4c32-9ac9-b54366a3d5e0" --dm-catalog-token "cloudConnectedToken"
Same comment as before, is this a fictional guid?

2023-12-19 15:11 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/CatalogService/HttpCatalogService.cs
> +		/// Starts the deployment process on a DataMiner Server. You'll need to call
Stopped midway with writing? Param, returns & exceptions aren't filled in either.

2023-12-19 15:11 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/Models/DeployedPackage.cs
> +	public class DeployedPackage
Add xml documentation

2023-12-20 08:55 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/DataMinerArtifacts/CatalogArtifact.cs
> +							keyFromEnv = keyFromWinEncryptedKeys;
As discussed in person. This is mostly from a user perspective, in most pipeline technology like jenkins/azure/github the use of regular 'unencrypted' environment variables is the industry standard. So we'll give priority to that above our custom tool that add additional encryption.
That way we can hopefully avoid confusion or unexpected behavior when a user manually runs the tool under a specific environment or by passing along the credentials.

So currently priority is given as follows:
1. your own provided credentials through arguments
2. your credentials provided through environment variable
3. your credentials provided through our custom Skyline.DataMiner.CICD.Tools.WinEncryptedKeys tool

2023-12-20 08:58 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/DataMinerArtifacts/IArtifact.cs
> +using System.Threading.Tasks;
Thanks!

2023-12-20 09:33 UTC, janstaelensskyline commented on CICD.Tools.DataminerDeploy/Program.cs
> +			description: "The unique cloud artifact identifier as returned from performing a catalog-upload. e.g. dmscript/f764389f-5404-4c32-9ac9-b54366a3d5e0")
It's the SkylineCommunications_AutomationScriptTest_SDK_DataAcq testing automationscript. Gets uploaded for the Skyline Communications organization only. So it should be safe.

2023-12-20 09:35 UTC, janstaelensskyline commented on CICD.Tools.DataminerDeploy/README.md
> +dataminer-package-deploy from-catalog --artifact-id "dmscript/f764389f-5404-4c32-9ac9-b54366a3d5e0" --dm-catalog-token "cloudConnectedToken"
It's the SkylineCommunications_AutomationScriptTest_SDK_DataAcq testing automationscript. Gets uploaded for the Skyline Communications organization only. So it should be safe.

2023-12-20 09:39 UTC, janstaelensskyline commented on CICD.Tools.DataminerDeploy/Program.cs
> +			var fromArtifact = new Command("from-artifact", "Deploys a specific package from a local .dmapp to a DataMiner agent.")
I removed everything concerning local artifacts from this branch. Including the readme & library items.
First release will be only for catalog due to SLNETTypes.dll issues with .netstandard for direct deployment through this .NET6.0 tool.

2023-12-20 09:42 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/CatalogService/HttpCatalogService.cs
> +		/// Starts the deployment process on a DataMiner Server. You'll need to call
Indeed, probably noticed halfway that this was an internal class.
I completed the comments.

2023-12-20 09:50 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/Models/DeployedPackage.cs
> +	public class DeployedPackage
done

2023-12-20 15:27 UTC, MichielOda requested changes

2023-12-20 15:27 UTC, MichielOda commented on CICD.Tools.DataminerDeploy/Program.cs
> +				if (!string.IsNullOrWhiteSpace(devopsMetricsMessage))
```suggestion
				if (!String.IsNullOrWhiteSpace(devopsMetricsMessage))
```

2023-12-20 16:28 UTC, merged