Dev/set to production
SkylineCommunications/Skyline.DataMiner.CICD.Tools.DataMinerDeploy pull request #7
Opened 2024-01-23 13:03 UTC by janstaelensskyline

Added the ability to specify a --post-action for deployment 'from-artifact'. In this case functionality was added to Set a protocol to production (and copy over templates or not) after deployment of a .dmprotocol.

2024-01-26 13:56 UTC, MichielOda requested changes

2024-01-26 13:56 UTC, MichielOda commented on CICD.Tools.DataminerDeploy/Program.cs
> +            deployTimeout.SetDefaultValue(15);
Description says 'in seconds' and default as 15 **minutes**. Default value should be 900 (15*60)

2024-01-26 13:56 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.DataminerDeploy.Lib/DataMinerService/SLNetDataMinerService.cs
> +                IInfo2 = int.MaxValue,
```suggestion
                bInfo1 = Int32.MaxValue,
                IInfo1 = Int32.MaxValue,
                IInfo2 = Int32.MaxValue,
```

2024-01-30 09:49 UTC, janstaelensskyline commented on CICD.Tools.DataminerDeploy/Program.cs
> +            deployTimeout.SetDefaultValue(15);
Adjusted to 900

2024-01-30 10:14 UTC, MichielOda approved these changes

2024-01-31 09:13 UTC, merged